[package]
name = "triangulate"
version = "0.1.0"
authors = ["Matt Keeter <matt.j.keeter@gmail.com>"]
edition = "2018"

[dependencies]
cdt = { path = "../cdt" }
nalgebra-glm = "0.3"
nurbs = { path = "../nurbs" }
rayon = "1.5"

[dev-dependencies]
clap = "2.33"
